// Generates src/icons/paths.ts from @phosphor-icons/core.
// The name map mirrors the design's icons.js (design icon name -> Phosphor icon), with duplicate keys
// resolved the way the browser resolved them (last one wins). Run: node scripts/gen-icons.js
const fs = require('fs');
const path = require('path');

const MAP = {
  'house': 'house-simple', 'home': 'house-simple', 'package': 'package', 'package-open': 'tray-arrow-down', 'package-check': 'package',
  'truck': 'truck', 'vault': 'vault', 'user': 'user', 'circle-user': 'user-circle', 'user-check': 'user-check',
  'chevron-left': 'caret-left', 'chevron-right': 'caret-right', 'chevron-down': 'caret-down', 'chevron-up': 'caret-up',
  'chevrons-up-down': 'caret-up-down', 'arrow-left': 'arrow-left', 'arrow-right': 'arrow-right',
  'check': 'check', 'circle-check': 'check-circle', 'badge-check': 'seal-check', 'circle': 'circle',
  'x': 'x', 'circle-x': 'x-circle', 'plus': 'plus', 'minus': 'minus',
  'search': 'magnifying-glass', 'search-x': 'magnifying-glass',
  'info': 'info', 'circle-alert': 'warning-circle', 'triangle-alert': 'warning', 'alert': 'warning-circle',
  'lock': 'lock-simple', 'shield-check': 'shield-check',
  'file-text': 'file-text', 'file-check': 'file-arrow-down', 'folder-open': 'folder-open', 'archive': 'archive',
  'clipboard-check': 'clipboard-text', 'clipboard-list': 'clipboard-text', 'barcode': 'barcode', 'scan-barcode': 'barcode', 'scan-line': 'scan',
  'printer': 'printer', 'signature': 'signature', 'pen-line': 'signature', 'warehouse': 'warehouse', 'building': 'buildings', 'building-2': 'buildings',
  'landmark': 'bank', 'map-pin': 'map-pin', 'map-pinned': 'map-pin-line', 'globe': 'globe', 'clock': 'clock',
  'calendar': 'calendar-blank', 'calendar-days': 'calendar-dots', 'paperclip': 'paperclip', 'upload': 'upload-simple', 'id-card': 'identification-card',
  'list-checks': 'list-checks', 'list': 'list-bullets', 'box': 'cube', 'layers': 'stack', 'coins': 'coins',
  'banknote': 'money', 'wallet': 'wallet', 'credit-card': 'credit-card', 'share': 'export', 'share-2': 'share-network',
  'activity': 'pulse', 'bell': 'bell-simple', 'eye': 'eye', 'eye-off': 'eye-slash', 'log-out': 'sign-out', 'phone': 'phone',
  'message-circle': 'chat-circle', 'mic': 'microphone', 'star': 'star', 'sliders-horizontal': 'sliders-horizontal',
  'locate-fixed': 'crosshair', 'navigation': 'navigation-arrow', 'headphones': 'headset',
  'loader-circle': 'spinner-gap', 'hand': 'handshake', 'gem': 'diamond', 'sparkles': 'info', 'arrow-left-right': 'arrows-left-right',
  'arrow-down-to-line': 'download-simple', 'download': 'download-simple', 'inbox': 'tray', 'hash': 'hash', 'align-left': 'text-align-left', 'tag': 'tag',
  'weight': 'scales', 'ruler': 'ruler', 'grid': 'squares-four', 'layout-grid': 'squares-four', 'sticky-note': 'note-pencil', 'map': 'map-trifold',
  'route': 'path', 'rotate-ccw': 'arrow-counter-clockwise', 'users': 'users', 'history': 'clock-counter-clockwise', 'settings': 'gear-six',
  'filter': 'funnel-simple', 'more-horizontal': 'dots-three', 'ellipsis': 'dots-three', 'camera': 'camera',
  // Not in icons.js (the prototype fell back to Lucide for these); closest Phosphor equivalents.
  'trash-2': 'trash', 'eraser': 'eraser', 'boxes': 'package', 'receipt': 'receipt', 'life-buoy': 'lifebuoy', 'flashlight': 'flashlight',
};
// Nav and tab icons also get the filled weight (active bottom-nav item).
const FILL = ['house', 'warehouse', 'circle-user', 'package-open', 'truck', 'vault'];

const root = path.join(__dirname, '..', 'node_modules', '@phosphor-icons', 'core', 'assets');
const read = (weight, ph) => {
  const file = path.join(root, weight, weight === 'regular' ? `${ph}.svg` : `${ph}-${weight}.svg`);
  const svg = fs.readFileSync(file, 'utf8');
  const ds = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  const others = svg.replace(/<svg[^>]*>|<\/svg>|<path d="[^"]+"\/>/g, '').trim();
  if (others) throw new Error(`${ph} (${weight}) has non-path elements: ${others}`);
  return ds.join(' ');
};

const out = {};
for (const [name, ph] of Object.entries(MAP)) {
  out[name] = { r: read('regular', ph) };
  if (FILL.includes(name)) out[name].f = read('fill', ph);
}
const body = Object.entries(out)
  .map(([k, v]) => `  '${k}': { r: '${v.r}'${v.f ? `, f: '${v.f}'` : ''} },`)
  .join('\n');
fs.writeFileSync(
  path.join(__dirname, '..', 'src', 'icons', 'paths.ts'),
  `// Generated by scripts/gen-icons.js from @phosphor-icons/core (viewBox 0 0 256 256). Do not edit.\n` +
    `export const ICON_PATHS: Record<string, { r: string; f?: string }> = {\n${body}\n};\n`,
);
console.log(`Wrote ${Object.keys(out).length} icons.`);
